name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - v1.**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.2

      # Runs a single command using the runners shell
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v12

      # Gives executions permissions to the build script
      - name: executions permissions to the build script
        run: chmod 700 ./build_web.sh

      # Runs the build script
      - name: Run the build script
        run: ./build_web.sh
        
      # commit the game files to github pages branch
      - name: Commit the game files to the github pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          BRANCH: gh-pages
          FOLDER: build_web

  build-win:
    name: Build (windows-latest)
    
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
         
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-7zip
    
    - name: Run the build script
      shell: cmd
      run: build_win32.bat
    
    - name: Rename build directory
      run: mv build_win32 Snake_win32
    
    - name: Compress the build dir
      run: 7z a -mx=9 Snake_win32.zip Snake_win32
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Snake_win32.zip
        asset_name: Snake_win32.zip
        tag: ${{ github.ref }}
        overwrite: true
